### ISSUE TITLE
Permission to use those stickers in my app 

### ISSUE THREAD

**Issue by AnasCode** [ptkdev/ptkdev-stickers#1]
Hello 
i'm wondering if i can use some of those stickers in my app for people to use in Whatsapp

**Comment by ptkdev** [comment]
You can, but exist [official whatsapp stickers app](https://stickers.ptkdev.io/whatsapp).

See [LICENSE](https://github.com/ptkdev/ptkdev-stickers/blob/master/LICENSE.md) and if you want commercial use [buy license](https://www.patreon.com/join/ptkdev/checkout?rid=3728641).
